# Generated by Django 2.2.6 on 2019-10-10 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_ID', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('card_ID', models.IntegerField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentItems',
            fields=[
                ('transaction_ID', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_status', models.BooleanField(default=False)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='liste.Item')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liste.Student')),
            ],
        ),
    ]
