# Generated by Django 2.2.6 on 2019-10-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentitems',
            old_name='current_price',
            new_name='transaction_price',
        ),
        migrations.AddField(
            model_name='studentitems',
            name='item_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='card_ID',
            field=models.IntegerField(null=True),
        ),
    ]
