# Generated by Django 2.2.6 on 2019-10-13 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0002_auto_20191013_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.BooleanField(default=True, verbose_name='Produkt Kategorie'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=100, verbose_name='Produkt Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Produkt Preis'),
        ),
        migrations.AlterField(
            model_name='student',
            name='card_ID',
            field=models.IntegerField(null=True, verbose_name='Kartennummer'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nickname',
            field=models.CharField(max_length=100, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='studentitems',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Produkt', to='liste.Item', verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='studentitems',
            name='item_count',
            field=models.PositiveIntegerField(verbose_name='Menge'),
        ),
        migrations.AlterField(
            model_name='studentitems',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name='Bezahlung erfolgt'),
        ),
        migrations.AlterField(
            model_name='studentitems',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liste.Student', verbose_name='Studierende'),
        ),
        migrations.AlterField(
            model_name='studentitems',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Rechnungsdatum'),
        ),
        migrations.AlterField(
            model_name='studentitems',
            name='transaction_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preis'),
        ),
    ]
