# Generated by Django 2.2.6 on 2019-10-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0003_auto_20191013_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='beer',
            field=models.BooleanField(default=False, verbose_name='Zählt für Bierliste?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.BooleanField(default=True, verbose_name='Erste Seite?'),
        ),
    ]
